// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Follow struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Permission struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Profile struct {
	UserID         uuid.UUID   `json:"user_id"`
	DisplayName    string      `json:"display_name"`
	Bio            pgtype.Text `json:"bio"`
	AvatarKey      pgtype.Text `json:"avatar_key"`
	Website        pgtype.Text `json:"website"`
	FollowersCount int64       `json:"followers_count"`
	FollowingCount int64       `json:"following_count"`
	PostsCount     int64       `json:"posts_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Role struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type Session struct {
	ID               string     `json:"id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	CsrfTokenHash    string     `json:"csrf_token_hash"`
	UserID           uuid.UUID  `json:"user_id"`
	DeviceName       string     `json:"device_name"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	Phone        pgtype.Text `json:"phone"`
	IsSuspended  bool        `json:"is_suspended"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID int32     `json:"role_id"`
}
