// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	Phone        sql.NullString `json:"phone"`
	Name         string         `json:"name"`
	IsSuspended  bool           `json:"is_suspended"`
	PasswordHash string         `json:"-"`
	VerifiedAt   *time.Time     `json:"verified_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
