// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID               string     `json:"id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	CsrfTokenHash    string     `json:"csrf_token_hash"`
	UserID           uuid.UUID  `json:"user_id"`
	DeviceName       string     `json:"device_name"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Name         string      `json:"name"`
	IsSuspended  bool        `json:"is_suspended"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
