// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
	user_id, display_name	
) VALUES ( $1, $2 )
	RETURNING user_id
`

type CreateProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.DisplayName)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE profiles
SET avatar_key = $1
WHERE user_id = $2
RETURNING user_id, avatar_key
`

type UpdateUserAvatarParams struct {
	AvatarKey pgtype.Text `json:"avatar_key"`
	UserID    uuid.UUID   `json:"user_id"`
}

type UpdateUserAvatarRow struct {
	UserID    uuid.UUID   `json:"user_id"`
	AvatarKey pgtype.Text `json:"avatar_key"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.AvatarKey, arg.UserID)
	var i UpdateUserAvatarRow
	err := row.Scan(&i.UserID, &i.AvatarKey)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE profiles
SET bio = COALESCE($1, bio),
    display_name = COALESCE($2, display_name),
    website = COALESCE($3, website)
WHERE user_id = $4
RETURNING user_id, bio, display_name, avatar_key, website
`

type UpdateUserProfileParams struct {
	Bio         pgtype.Text `json:"bio"`
	DisplayName pgtype.Text `json:"display_name"`
	Website     pgtype.Text `json:"website"`
	UserID      uuid.UUID   `json:"user_id"`
}

type UpdateUserProfileRow struct {
	UserID      uuid.UUID   `json:"user_id"`
	Bio         pgtype.Text `json:"bio"`
	DisplayName string      `json:"display_name"`
	AvatarKey   pgtype.Text `json:"avatar_key"`
	Website     pgtype.Text `json:"website"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Bio,
		arg.DisplayName,
		arg.Website,
		arg.UserID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Website,
	)
	return i, err
}
