// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
}

var _ Querier = (*Queries)(nil)
