// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
	id, user_id, refresh_token_hash, csrf_token_hash, device_name, expires_at
) VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING id, user_id, refresh_token_hash, csrf_token_hash, device_name, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID               string    `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	CsrfTokenHash    string    `json:"csrf_token_hash"`
	DeviceName       string    `json:"device_name"`
	ExpiresAt        time.Time `json:"expires_at"`
}

type CreateSessionRow struct {
	ID               string     `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	CsrfTokenHash    string     `json:"csrf_token_hash"`
	DeviceName       string     `json:"device_name"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.CsrfTokenHash,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CsrfTokenHash,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT 
    s.id,
    s.user_id,
    s.refresh_token_hash,
    s.csrf_token_hash,
    s.device_name,
    s.expires_at,
    s.revoked_at,
	u.verified_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
`

type GetUserSessionRow struct {
	ID               string     `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	CsrfTokenHash    string     `json:"csrf_token_hash"`
	DeviceName       string     `json:"device_name"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	VerifiedAt       *time.Time `json:"verified_at"`
}

func (q *Queries) GetUserSession(ctx context.Context, id string) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, id)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CsrfTokenHash,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.VerifiedAt,
	)
	return i, err
}
