// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	id, email, name, password_hash, username 
) VALUES ( $1, $2, $3, $4, $5 )
RETURNING id, email, name, username, password_hash, verified_at, created_at, updated_at, is_suspended, phone
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"-"`
	Username     string    `json:"username"`
}

type CreateUserRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	IsSuspended  bool        `json:"is_suspended"`
	Phone        pgtype.Text `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Username,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
		&i.Phone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, username, password_hash, verified_at, created_at, updated_at, is_suspended, phone 
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	IsSuspended  bool        `json:"is_suspended"`
	Phone        pgtype.Text `json:"phone"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
		&i.Phone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, username, password_hash, verified_at, created_at, updated_at, is_suspended, phone 
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	IsSuspended  bool        `json:"is_suspended"`
	Phone        pgtype.Text `json:"phone"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
		&i.Phone,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
	SET password_hash = $1
	WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"-"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verifyUserEmail = `-- name: VerifyUserEmail :execrows
UPDATE users
	SET verified_at = CURRENT_TIMESTAMP
	WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, verifyUserEmail, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
