// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	id, email, password_hash, username 
) VALUES ( $1, $2, $3, $4 )
RETURNING id, email, username, password_hash, verified_at, created_at, updated_at, is_suspended, phone
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"-"`
	Username     string    `json:"username"`
}

type CreateUserRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	IsSuspended  bool        `json:"is_suspended"`
	Phone        pgtype.Text `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
		&i.Phone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, verified_at, created_at, updated_at, is_suspended, phone 
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"-"`
	VerifiedAt   *time.Time  `json:"verified_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	IsSuspended  bool        `json:"is_suspended"`
	Phone        pgtype.Text `json:"phone"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
		&i.Phone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id,
    u.email,
    u.username,
    u.verified_at,
    u.created_at,
    u.updated_at,
	u.password_hash,
    u.is_suspended,
    u.phone,

    p.display_name,
    p.bio,
    p.avatar_key,
    p.website,
    p.followers_count,
    p.following_count,
    p.posts_count,
    p.created_at AS profile_created_at,
    p.updated_at AS profile_updated_at

FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID               uuid.UUID   `json:"id"`
	Email            string      `json:"email"`
	Username         string      `json:"username"`
	VerifiedAt       *time.Time  `json:"verified_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	PasswordHash     string      `json:"-"`
	IsSuspended      bool        `json:"is_suspended"`
	Phone            pgtype.Text `json:"phone"`
	DisplayName      pgtype.Text `json:"display_name"`
	Bio              pgtype.Text `json:"bio"`
	AvatarKey        pgtype.Text `json:"avatar_key"`
	Website          pgtype.Text `json:"website"`
	FollowersCount   pgtype.Int8 `json:"followers_count"`
	FollowingCount   pgtype.Int8 `json:"following_count"`
	PostsCount       pgtype.Int8 `json:"posts_count"`
	ProfileCreatedAt *time.Time  `json:"profile_created_at"`
	ProfileUpdatedAt *time.Time  `json:"profile_updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsSuspended,
		&i.Phone,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.Website,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.PostsCount,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
	SET password_hash = $1
	WHERE id = $2
RETURNING id
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"-"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
	SET verified_at = CURRENT_TIMESTAMP
	WHERE id = $1
RETURNING id
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
